### ISSUE TITLE
yield is a keyword inside the body of a non-strict generator function

### ISSUE THREAD

**Issue by mohsen1** [shapesecurity/shift-parser-js#238]
``` js
shift.parseScript(`
 function* foo(){
   var yield = 1
 }`)
```

should throw

**Comment by michaelficarra** [comment]
Confirmed. GeneratorBody sets the Yield flag on FunctionBody, the intermediate nodes all pass the flag through unchanged, and BindingIdentifier only allows `yield` if the Yield flag is not set.

**Comment by michaelficarra** [comment]
It is strange that this parse succeeds, considering we already have [this test for parse failure](https://github.com/shapesecurity/shift-parser-js/blob/738858bedc856cd10831b3e783dadba2361a0498/test/declaration/generator-declaration.js#L179).

**Comment by michaelficarra** [comment]
Ugh, I can no longer reproduce this...

```
$ node
> require("./").parseScript("function* a() { var yield; }")
Error: [1:21]: Unexpected token "yield"
>
```

I'm not sure what was wrong before, but a clean build seemed to have fixed it. @mohsen1 Are you working in a fresh clone of the es6 branch? If not, please try that. This may have been fixed since the last release.

**Comment by mohsen1** [comment]
I wasn't on my main computer when I reported this. Ran that snippet in browser console of visualizer. It's still happening there but I would assume visualizer is using an older version.

**Comment by michaelficarra** [comment]
Yes, the visualiser is a bit outdated right now. If you can reproduce this on the es6 branch, please re-open.
